In [185]:
import pandas
import pandera

In [186]:
df = pandas.read_excel('dataframe_fo.xlsx', sheet_name="fo-op")
df.head(10)

,level_id,unit_id,distance_to_soti,distance_to_distribution_board,connector_id,number_of_cables,cables_setup,total_cable_attenuation,total_unit_attenuation
0,1,101,1,34,1,2,2:1 1:1,0.0140,0.7140
1,1,112,1,34,1,2,2:1 1:1,0.0140,0.7140
2,1,102,1,29,1,2,2:1 1:1,0.0120,0.7120
3,1,111,1,29,1,2,2:1 1:1,0.0120,0.7120
4,1,106,1,27,1,2,2:1 1:1,0.0112,0.7112
5,1,107,1,27,1,2,2:1 1:1,0.0112,0.7112
6,1,108,1,20,1,2,2:1 1:1,0.0084,0.7084
7,1,110,1,20,1,2,2:1 1:1,0.0084,0.7084
8,1,105,1,19,1,2,2:1 1:1,0.0080,0.7080
9,1,103,1,18,1,2,2:1 1:1,0.0076,0.7076

In [187]:
for column in df.columns:   
    print(f"{column}:" , df[column].dtype)

level_id: int64
unit_id: int64
distance_to_soti: int64
distance_to_distribution_board: int64
connector_id: int64
number_of_cables: int64
cables_setup: object
total_cable_attenuation: float64
total_unit_attenuation: float64

In [188]:
df.columns

Index(['level_id', 'unit_id', 'distance_to_soti',
       'distance_to_distribution_board', 'connector_id', 'number_of_cables',
       'cables_setup', 'total_cable_attenuation', 'total_unit_attenuation'],
      dtype='object')

In [189]:
df2 = df[["level_id", 'unit_id']]
df2.head()

   level_id  unit_id
0         1      101
1         1      112
2         1      102
3         1      111
4         1      106

In [190]:
df3 = pandas.DataFrame({})

In [191]:
schema = pandera.DataFrameSchema({
    "level_id": pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    "unit_id": pandera.Column(str, nullable=False, required=True, coerce=True), 
    "distance_to_soti": pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True), 
    "distance_to_distribution_board": pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True), 
    "connector_id": pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=False),  
    "number_of_cables": pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True), 
    "cables_setup": pandera.Column(str, nullable=False, required=True),  
    "total_cable_attenuation": pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True), 
    "total_unit_attenuation": pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True), 
    })

# if schema.validate(df, lazy=True)==True:
#     print('yes')

schema.validate(df, lazy=True).head()

,level_id,unit_id,distance_to_soti,distance_to_distribution_board,connector_id,number_of_cables,cables_setup,total_cable_attenuation,total_unit_attenuation
0,1,101,1,34,1,2,2:1 1:1,0.0140,0.7140
1,1,112,1,34,1,2,2:1 1:1,0.0140,0.7140
2,1,102,1,29,1,2,2:1 1:1,0.0120,0.7120
3,1,111,1,29,1,2,2:1 1:1,0.0120,0.7120
4,1,106,1,27,1,2,2:1 1:1,0.0112,0.7112

In [192]:
for column in schema.validate(df, lazy=True).columns: 
    print(f"{column}:" , schema.validate(df, lazy=True)[column].dtype)

level_id: int64
unit_id: object
distance_to_soti: int64
distance_to_distribution_board: int64
connector_id: int64
number_of_cables: int64
cables_setup: object
total_cable_attenuation: float64
total_unit_attenuation: float64

In [193]:
df_wired_coaxial = pandas.read_excel("./dataframe_wired_coaxial.xlsx", sheet_name='catv-backbones-op-0')
df_wired_coaxial.head(10)

,level_id,unit_id,distance_to_soti,distance_to_sots,distance_to_distribution_board,backbone_cable_id,lateral_net_cable_id,connector_id,derivator_id,backbone_index,...,connector_attenuation,backbone_cable_attenuation_with_47mhz,backbone_cable_attenuation_with_1350mhz,lateral_net_cable_attenuation_with_47mhz,lateral_net_cable_attenuation_with_1350mhz,derivator_attenuation,derivator_step_attenuation,cumulative_level_derivator_step_attenuation,total_attenuation_with_47mhz,total_attenuation_with_1350mhz
0,1,102A,33.0,19.6,25,T200PLUS,T100PLUS,1,457403,0,...,0.30,0.660,4.95,0.75,5.50,18.5,2.0,0.0,24.210,33.25
1,1,103A,33.0,19.6,25,T200PLUS,T100PLUS,1,457403,0,...,0.30,0.660,4.95,0.75,5.50,18.5,2.0,0.0,24.210,33.25
2,1,104A,33.0,19.6,17,T200PLUS,T100PLUS,1,457403,0,...,0.30,0.660,4.95,0.51,3.74,18.5,2.0,0.0,23.970,31.49
3,1,101A,33.0,19.6,15,T200PLUS,T100PLUS,1,457403,0,...,0.30,0.660,4.95,0.45,3.30,18.5,2.0,0.0,23.910,31.05
4,2,204A,35.4,17.2,25,T200PLUS,T100PLUS,1,457903,0,...,0.45,0.708,5.31,0.75,5.50,16.0,5.5,2.0,23.908,33.26
5,2,205A,35.4,17.2,24,T200PLUS,T100PLUS,1,457903,0,...,0.45,0.708,5.31,0.72,5.28,16.0,5.5,2.0,23.878,33.04
6,2,201A,35.4,17.2,23,T200PLUS,T100PLUS,1,457903,0,...,0.45,0.708,5.31,0.69,5.06,16.0,5.5,2.0,23.848,32.82
7,2,209A,35.4,17.2,16,T200PLUS,T100PLUS,1,457903,0,...,0.45,0.708,5.31,0.48,3.52,16.0,5.5,2.0,23.638,31.28
8,2,203A,35.4,17.2,15,T200PLUS,T100PLUS,1,457903,0,...,0.45,0.708,5.31,0.45,3.30,16.0,5.5,2.0,23.608,31.06
9,2,202A,35.4,17.2,14,T200PLUS,T100PLUS,1,457903,0,...,0.45,0.708,5.31,0.42,3.08,16.0,5.5,2.0,23.578,30.84

In [194]:
df_wired_coaxial.columns

Index(['level_id', 'unit_id', 'distance_to_soti', 'distance_to_sots',
       'distance_to_distribution_board', 'backbone_cable_id',
       'lateral_net_cable_id', 'connector_id', 'derivator_id',
       'backbone_index', 'derivator_index', 'splitter_attenuation',
       'connector_attenuation', 'backbone_cable_attenuation_with_47mhz',
       'backbone_cable_attenuation_with_1350mhz',
       'lateral_net_cable_attenuation_with_47mhz',
       'lateral_net_cable_attenuation_with_1350mhz', 'derivator_attenuation',
       'derivator_step_attenuation',
       'cumulative_level_derivator_step_attenuation',
       'total_attenuation_with_47mhz', 'total_attenuation_with_1350mhz'],
      dtype='object')

In [195]:
df_wired_coaxial['distance_to_sots'].dtype

dtype('float64')

In [196]:
for column in df_wired_coaxial.columns:   
    print(f"{column}:" , df_wired_coaxial[column].dtype)

level_id: int64
unit_id: object
distance_to_soti: float64
distance_to_sots: float64
distance_to_distribution_board: int64
backbone_cable_id: object
lateral_net_cable_id: object
connector_id: int64
derivator_id: int64
backbone_index: int64
derivator_index: int64
splitter_attenuation: int64
connector_attenuation: float64
backbone_cable_attenuation_with_47mhz: float64
backbone_cable_attenuation_with_1350mhz: float64
lateral_net_cable_attenuation_with_47mhz: float64
lateral_net_cable_attenuation_with_1350mhz: float64
derivator_attenuation: float64
derivator_step_attenuation: float64
cumulative_level_derivator_step_attenuation: float64
total_attenuation_with_47mhz: float64
total_attenuation_with_1350mhz: float64

In [197]:
df_wired_coaxial_with_amplifier = pandas.read_excel("./dataframe_wired_coaxial_with_amplifier.xlsx", sheet_name='catv-amplifiers-op-2')
df_wired_coaxial_with_amplifier.head(10)

,level_id,unit_id,distance_to_soti,distance_to_sots,distance_to_distribution_board,backbone_cable_id,lateral_net_cable_id,connector_id,derivator_id,backbone_index,...,derivator_attenuation,derivator_step_attenuation,cumulative_level_derivator_step_attenuation,total_attenuation_with_47mhz,total_attenuation_with_1350mhz,amplifier_id,amplifier_index,amplifier_power,total_attenuation_amplifiers_with_47mhz,total_attenuation_amplifiers_with_1350mhz
0,1,Local 21,15.0,41.2,31,T200PLUS,T100PLUS,1,457403,0,...,18.5,2.0,0.0,24.030,31.87,1,0,0.0,24.030,31.87
1,1,Local 20,15.0,41.2,28,T200PLUS,T100PLUS,1,457403,0,...,18.5,2.0,0.0,23.940,31.21,1,0,0.0,23.940,31.21
2,1,Local 19,15.0,41.2,25,T200PLUS,T100PLUS,1,457403,0,...,18.5,2.0,0.0,23.850,30.55,1,0,0.0,23.850,30.55
3,1,Local 18,15.0,41.2,24,T200PLUS,T100PLUS,1,457403,0,...,18.5,2.0,0.0,23.820,30.33,1,0,0.0,23.820,30.33
4,1,Local 17,15.0,41.2,19,T200PLUS,T100PLUS,1,457403,0,...,18.5,2.0,2.0,25.670,31.23,1,0,0.0,25.670,31.23
5,1,Local 13,15.0,41.2,15,T200PLUS,T100PLUS,1,457403,0,...,18.5,2.0,2.0,25.550,30.35,1,0,0.0,25.550,30.35
6,1,Local 16,15.0,41.2,14,T200PLUS,T100PLUS,1,457403,0,...,18.5,2.0,2.0,25.520,30.13,1,0,0.0,25.520,30.13
7,1,Local 14,15.0,41.2,11,T200PLUS,T100PLUS,1,457403,0,...,18.5,2.0,2.0,25.430,29.47,1,0,0.0,25.430,29.47
8,1,Local 15,15.0,41.2,8,T200PLUS,T100PLUS,1,456203,0,...,12.5,2.5,4.0,21.340,24.81,1,0,0.0,21.340,24.81
9,2,208,17.4,38.8,39,T200PLUS,T100PLUS,1,457403,1,...,18.5,2.0,0.0,24.318,33.99,1,0,0.0,24.318,33.99

In [198]:
df_wired_coaxial_with_amplifier.columns

Index(['level_id', 'unit_id', 'distance_to_soti', 'distance_to_sots',
       'distance_to_distribution_board', 'backbone_cable_id',
       'lateral_net_cable_id', 'connector_id', 'derivator_id',
       'backbone_index', 'derivator_index', 'splitter_attenuation',
       'connector_attenuation', 'backbone_cable_attenuation_with_47mhz',
       'backbone_cable_attenuation_with_1350mhz',
       'lateral_net_cable_attenuation_with_47mhz',
       'lateral_net_cable_attenuation_with_1350mhz', 'derivator_attenuation',
       'derivator_step_attenuation',
       'cumulative_level_derivator_step_attenuation',
       'total_attenuation_with_47mhz', 'total_attenuation_with_1350mhz',
       'amplifier_id', 'amplifier_index', 'amplifier_power',
       'total_attenuation_amplifiers_with_47mhz',
       'total_attenuation_amplifiers_with_1350mhz'],
      dtype='object')

In [199]:
for column in df_wired_coaxial_with_amplifier.columns:   
    print(f"{column}:" , df_wired_coaxial_with_amplifier[column].dtype)

level_id: int64
unit_id: object
distance_to_soti: float64
distance_to_sots: float64
distance_to_distribution_board: int64
backbone_cable_id: object
lateral_net_cable_id: object
connector_id: int64
derivator_id: int64
backbone_index: int64
derivator_index: int64
splitter_attenuation: int64
connector_attenuation: float64
backbone_cable_attenuation_with_47mhz: float64
backbone_cable_attenuation_with_1350mhz: float64
lateral_net_cable_attenuation_with_47mhz: float64
lateral_net_cable_attenuation_with_1350mhz: float64
derivator_attenuation: float64
derivator_step_attenuation: float64
cumulative_level_derivator_step_attenuation: float64
total_attenuation_with_47mhz: float64
total_attenuation_with_1350mhz: float64
amplifier_id: int64
amplifier_index: int64
amplifier_power: float64
total_attenuation_amplifiers_with_47mhz: float64
total_attenuation_amplifiers_with_1350mhz: float64

# Conditional to diference between with amplifier or without amplifier

In [200]:
def verify_dataframe(df_1: pandas.DataFrame, df_2: pandas.DataFrame) -> str:
    print("estas columnas no esta en df_2:")
    for column_1 in df_1.columns:
        if column_1 in df_2.columns:
            pass
        else:
            print(f"{column_1}", df_1[column_1].dtype)
    
    print("\nestas columnas no esta en df_1:")
    for column_2 in df_2.columns:
        if column_2 in df_1.columns:
            pass
        else:
            print(f"{column_2}", df_2[column_2].dtype)

In [201]:
verify_dataframe(df_1=df_wired_coaxial, df_2=df_wired_coaxial_with_amplifier)

estas columnas no esta en df_2:

estas columnas no esta en df_1:
amplifier_id int64
amplifier_index int64
amplifier_power float64
total_attenuation_amplifiers_with_47mhz float64
total_attenuation_amplifiers_with_1350mhz float64

In [202]:
schema = pandera.DataFrameSchema({
    'level_id': pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'unit_id': pandera.Column(str, nullable=False, required=True),
    'distance_to_soti': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'distance_to_sots': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'distance_to_distribution_board': pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'backbone_cable_id': pandera.Column(str, nullable=False, required=True),
    'lateral_net_cable_id': pandera.Column(str, nullable=False, required=True),
    'connector_id': pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'derivator_id': pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'backbone_index': pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'derivator_index': pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'splitter_attenuation': pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'connector_attenuation': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'backbone_cable_attenuation_with_47mhz': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'backbone_cable_attenuation_with_1350mhz': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'lateral_net_cable_attenuation_with_47mhz': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'lateral_net_cable_attenuation_with_1350mhz': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'derivator_attenuation': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'derivator_step_attenuation': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'cumulative_level_derivator_step_attenuation': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'total_attenuation_with_47mhz': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'total_attenuation_with_1350mhz': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'amplifier_id': pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'amplifier_index': pandera.Column(int, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'amplifier_power': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'total_attenuation_amplifiers_with_47mhz': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True),
    'total_attenuation_amplifiers_with_1350mhz': pandera.Column(float, pandera.Check(lambda x: x >= 0), nullable=False, required=True)
    })

In [206]:
if schema.validate(df_wired_coaxial_with_amplifier, lazy=True).columns.all() == df_wired_coaxial_with_amplifier.columns.all():
    print('yeah')

yeah

In [214]:
type(schema.validate(df_wired_coaxial_with_amplifier, lazy=True))

pandas.core.frame.DataFrame

In [205]:
schema.validate(df_wired_coaxial, lazy=True).head()

SchemaErrors: A total of 5 schema errors were found.

Error Counts
------------
- column_not_in_dataframe: 5

Schema Error Summary
--------------------
                                                                                                                                                                   failure_cases  n_failure_cases
schema_context  column check
DataFrameSchema <NA>   column_in_dataframe  [amplifier_id, amplifier_power, amplifier_index, total_attenuation_amplifiers_with_47mhz, total_attenuation_amplifiers_with_1350mhz]                5

Usage Tip
---------

Directly inspect all errors by catching the exception:

```
try:
    schema.validate(dataframe, lazy=True)
except SchemaErrors as err:
    err.failure_cases  # dataframe of schema errors
    err.data  # invalid dataframe
```

In [ ]:

    # def _validate_dataframe_is_not_empty(self):
    #     if self.value.empty:
    #         raise NotFoundException("DataFrame is empty")    
    
    # def _validate_dataframe_has_column_valid_value_of_columns(self):
    #     value_df = self.value
    #     for filter_column in self._filter_columns:
    #         if filter_column not in self.value.columns:
    #             raise ArgumentInvalidException(f"DataFrame has not found column {filter_column}")